
// This file has been generated by the GUI designer. Do not modify.
namespace bitclean.Systems.learning
{
	public partial class learningtypes
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget bitclean.Systems.learning.learningtypes
			this.Name = "bitclean.Systems.learning.learningtypes";
			this.Title = global::Mono.Unix.Catalog.GetString("learningtypes");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
